name: CI

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - master
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  label-detector:
    name: Runner Label
    runs-on: label-detector
    outputs:
      runs-on: ${{ steps.detector.outputs.label }}
    steps:
      - name: Detect Label
        id: detector
        run: |
          # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idoutputs
          echo "label=$(curl -fsSL https://this-is-nats.appscode.ninja/runs-on/${{ github.repository_owner }}?visibility=${{ github.repository_visibility }})" >> $GITHUB_OUTPUT

  build:
    name: Build
    needs: label-detector
    runs-on: "${{ needs.label-detector.outputs.runs-on }}"
    steps:
      - name: Set up Go 1.23
        uses: actions/setup-go@v1
        with:
          go-version: '1.23'
        id: go

      - name: Use Node.js 20.x
        uses: actions/setup-node@v2
        with:
          node-version: '20'
          check-latest: true

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Prepare git
        env:
          GITHUB_USER: 1gtm
          GITHUB_TOKEN: ${{ secrets.LGTM_GITHUB_TOKEN }}
        run: |
          set -x
          git config --global user.name "${GITHUB_USER}"
          git config --global user.email "${GITHUB_USER}@appscode.com"
          git config --global \
            url."https://${GITHUB_USER}:${GITHUB_TOKEN}@github.com".insteadOf \
            "https://github.com"

      - name: Run checks
        run: |
          sudo apt-get -qq update || true
          make ci
